// <auto-generated />
using System;
using ConcediuAngajati.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConcediuAngajati.Migrations
{
    [DbContext(typeof(ConcediuAngajatiContext))]
    partial class ConcediuAngajatiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ConcediuAngajati.Models.Angajat", b =>
                {
                    b.Property<int>("AngajatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataNastere")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenume")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AngajatId");

                    b.ToTable("Angajati");
                });

            modelBuilder.Entity("ConcediuAngajati.Models.AngajatConcediu", b =>
                {
                    b.Property<int>("AngajatConcediuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AngajatId")
                        .HasColumnType("int");

                    b.Property<int>("ConcediuId")
                        .HasColumnType("int");

                    b.Property<int>("ZileConcediuDisponibile")
                        .HasColumnType("int");

                    b.Property<int>("ZileConcediuUtilizate")
                        .HasColumnType("int");

                    b.HasKey("AngajatConcediuId");

                    b.HasIndex("AngajatId");

                    b.HasIndex("ConcediuId");

                    b.ToTable("AngajatiConcedii");
                });

            modelBuilder.Entity("ConcediuAngajati.Models.AngajatFunctie", b =>
                {
                    b.Property<int>("AngajatFunctieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AngajatId")
                        .HasColumnType("int");

                    b.Property<int>("FunctieId")
                        .HasColumnType("int");

                    b.HasKey("AngajatFunctieId");

                    b.HasIndex("AngajatId");

                    b.HasIndex("FunctieId");

                    b.ToTable("AngajatiFunctii");
                });

            modelBuilder.Entity("ConcediuAngajati.Models.CerereConcediu", b =>
                {
                    b.Property<int>("CerereId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AngajatId")
                        .HasColumnType("int");

                    b.Property<string>("Descriere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CerereId");

                    b.HasIndex("AngajatId");

                    b.ToTable("CereriConcediu");
                });

            modelBuilder.Entity("ConcediuAngajati.Models.Concediu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NrZile")
                        .HasColumnType("int");

                    b.Property<string>("TipConcediu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Concedii");
                });

            modelBuilder.Entity("ConcediuAngajati.Models.Functie", b =>
                {
                    b.Property<int>("FunctieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descriere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipFunctie")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FunctieId");

                    b.ToTable("Functii");
                });

            modelBuilder.Entity("ConcediuAngajati.Models.AngajatConcediu", b =>
                {
                    b.HasOne("ConcediuAngajati.Models.Angajat", "Angajat")
                        .WithMany("AngajatiConcedii")
                        .HasForeignKey("AngajatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConcediuAngajati.Models.Concediu", "Concediu")
                        .WithMany("AngajatiConcedii")
                        .HasForeignKey("ConcediuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConcediuAngajati.Models.AngajatFunctie", b =>
                {
                    b.HasOne("ConcediuAngajati.Models.Angajat", "Angajat")
                        .WithMany()
                        .HasForeignKey("AngajatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConcediuAngajati.Models.Functie", "Functie")
                        .WithMany("AngajatiFunctii")
                        .HasForeignKey("FunctieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConcediuAngajati.Models.CerereConcediu", b =>
                {
                    b.HasOne("ConcediuAngajati.Models.Angajat", "Angajat")
                        .WithMany("CereriConcediu")
                        .HasForeignKey("AngajatId");
                });
#pragma warning restore 612, 618
        }
    }
}
